# Generated by Django 5.0.7 on 2024-08-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date'], 'verbose_name': 'articleInfo'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='publish_data',
            new_name='publish_date',
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
