# Generated by Django 5.1.2 on 2024-10-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': '电影管理', 'verbose_name_plural': '电影管理'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='actor',
            new_name='actors',
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='时长(或集数)'),
        ),
    ]
