# Generated by Django 5.0.7 on 2024-08-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(help_text='best size: 500x755', upload_to='team', verbose_name='avatar name')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
            ],
            options={
                'verbose_name': 'teams',
                'verbose_name_plural': 'teams',
                'db_table': 'teams',
            },
        ),
    ]
