# Generated by Django 5.0.7 on 2024-08-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='order'),
            preserve_default=False,
        ),
    ]
