# Generated by Django 5.1 on 2024-08-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_name', models.CharField(max_length=120, unique=True, verbose_name='Grade Name')),
                ('grade_number', models.CharField(max_length=10, unique=True, verbose_name='Grade Number')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grade',
                'db_table': 'grade',
            },
        ),
    ]
