# Generated by Django 5.1 on 2024-08-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Grade', 'verbose_name_plural': 'Grade Information'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_name',
            field=models.CharField(max_length=120, unique=True, verbose_name='班级名称'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='班级编号'),
        ),
    ]
