# Generated by Django 5.1 on 2024-09-21 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_alter_grade_options'),
        ('teachers', '0002_rename_contact_number_teacher_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teachers', to='grades.grade', verbose_name='管理班级'),
        ),
    ]
