# Generated by Django 4.2.3 on 2023-07-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
