# Generated by Django 5.0.7 on 2024-08-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slide',
            table='slides',
        ),
    ]
