# Generated by Django 4.2.3 on 2023-07-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_rename_create_at_lead_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='eamil',
            new_name='email',
        ),
    ]
