# Generated by Django 4.2 on 2024-04-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='model',
            new_name='content',
        ),
    ]
