# Generated by Django 4.2 on 2024-04-04 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_model_blogpost_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='published_data',
            new_name='published_date',
        ),
    ]
