# Generated by Django 5.0.7 on 2024-08-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='best size: 1920x1280', upload_to='slide', verbose_name='slide name')),
                ('title', models.CharField(help_text='heading 1', max_length=200, verbose_name='title')),
                ('content', models.CharField(help_text='heading 2', max_length=200, verbose_name='contetn')),
            ],
            options={
                'verbose_name': 'Slide Management',
                'verbose_name_plural': 'Slide Management',
            },
        ),
    ]
