# Generated by Django 5.0.7 on 2024-08-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
