# Generated by Django 5.0.7 on 2024-08-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'userInfo'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
