# Generated by Django 5.0.7 on 2024-08-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passworkd',
            new_name='password',
        ),
    ]
